### ISSUE TITLE
Inner reads unexpected EOF

### ISSUE THREAD

**Issue by mTsBucy1** [SebRollen/tower-github-webhook#1]
Hi there, I have some questions about this crate.

- By reading the future code and the fact that my handler throws an error, because it reached unexpected EOF, it seems that this layer completely "empties" the request body, meaning any inner service cannot simply read the request body.
- I am therefore confused, whether you have gotten this layer to work properly with a useful handler?
- Next, when looking at the `simple` example with my mediocre axum knowledge, it seems that the `FromRequest` for `Event` wouldn't be used, since `Event` is wrapped in the JSON extractor. Do I misunderstand something there?

Thanks for developing this crate, it would be exactly what I need 😄

**Comment by SebRollen** [comment]
Hi @mTsBucy1,

Yes, you're completely right—I need to add a disclaimer to the README that this crate is currently not functioning as intended. The body gets emptied and not passed on to the inner handler.

I have not had time to come back and fix the issue yet unfortunately, and honestly wasn't expecting anyone to come across the crate and use it. I'll add a note to the README now and yank any crates.io versions until I have the time to come back and refactor.

Sorry for any confusion!

**Comment by SebRollen** [comment]
Alright, I've yanked the versions from crates.io.

@mTsBucy1, if you're interested in getting this working, the logic that needs to get updated is in this section: https://github.com/SebRollen/tower-github-webhook/blob/main/src/future.rs#L92-L120

Two ways I could think of fixing this issue:
1. Update the trait bounds for `ReqBody` to be `Clone`, and storing the inner body somewhere to pass on to the inner service
2. Reading the bytes from the body into some buffer stored inside `ValidateGitHubWebhookFuture` and rebuilding the body from that buffer before passing it to the inner service

**Comment by mTsBucy1** [comment]
Okay, that makes sense.

So found an example from axum here: https://github.com/tokio-rs/axum/blob/main/examples/consume-body-in-extractor-or-middleware/src/main.rs which talks about this problem. Their solution is essentially to collect into bytes first, which would be fairly straight forward to implement. However, your decision to implement your own future makes it a bit more complex.

I'm going to try this, but I'll also time limit myself, to not get sucked into a huge rabbit hole xD

**Comment by SebRollen** [comment]
Thanks for the link, will check that out.

If you're just looking for a quick solution for your use-case, I've used this middleware function before to do the same thing that this crate is attempting to do:

In `middleware.rs`
```rust
use crate::error::Error;
use crate::AppState;
use axum::{extract::State, http::Request, middleware::Next, response::Response};
use hmac::{Hmac, Mac};
use hyper::body::to_bytes;
use sha2::Sha256;

pub async fn verify_github_webhook(
    State(state): State<AppState>,
    request: Request<hyper::Body>,
    next: Next<hyper::Body>,
) -> Response {
    let (parts, body) = request.into_parts();
    let mut hmac =
        Hmac::<Sha256>::new_from_slice(state.github_settings().webhook_secret.as_bytes())
            .expect("HMAC can take key of any size");
    let signature = match parts.headers.get("x-hub-signature-256") {
        Some(sig) => {
            let sig = sig
                .as_bytes()
                .splitn(2, |x| x == &b'=')
                .nth(1)
                .expect("Unexpected format for GitHub signature");
            hex::decode(sig).expect("Unexpected format for GitHub signature")
        }
        None => return Error::unauthorized(),
    };
    let message = match to_bytes(body).await {
        Ok(bytes) => bytes,
        Err(_) => return Error::unauthorized(),
    };
    hmac.update(&message);
    if hmac.verify_slice(&signature).is_ok() {
        tracing::trace!("GitHub webhook verified");
        let request = Request::from_parts(parts, hyper::Body::from(message));
        next.run(request).await
    } else {
        tracing::warn!("GitHub webhook failed verification");
        Error::unauthorized()
    }
}
```

and then in my axum router:
```rust
Router::new()
        .route(
            "/events",
            post(handle_event).route_layer(middleware::from_fn_with_state(
                state,
                crate::middleware::verify_github_webhook,
            )),
        )
```

**Comment by SebRollen** [comment]
@mTsBucy1 had some time on a flight yesterday and was able to get this working, including fixing the example (you're right that the JSON extractor was not needed).

Thanks again for the report!
